version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: nest-app
    ports:
      - 3001:3001
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_cinema_db
    volumes:
      - ./data:/var/lib/mysql
